project_id = "rnzowsdzzozmrclvbpum"

[functions.predict-harvesting]
verify_jwt = false

[functions.chatbot]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false
